
ICD9CODES = {
    '008.45': 'Intestinal infection due to clostridium difficile',
    '038.9': 'Unspecified septicemia',
    '070.54': 'Chronic hepatitis C without mention of hepatic coma',
    '197.2': 'Secondary malignant neoplasm of pleura',
    '238.4': 'Polycythemia vera',
    '238.71': 'Essential thrombocythemia',
    '244.9': 'Unspecified hypothyroidism',
    '250.00': 'type II diabetes mellitus [non-insulin dependent type] [NIDDM type] [adult-onset type] or unspecified type, not stated as uncontrolled, without mention of complication',
    '261': 'Nutritional marasmus',
    '263.9': 'Unspecified protein-calorie malnutrition',
    '272.0': 'Pure hypercholesterolemia',
    '272.4': 'Other and unspecified hyperlipidemia',
    '274.9': 'Gout, unspecified',
    '276.0': 'Hyperosmolality and/or hypernatremia',
    '276.1': 'Hyposmolality and/or hyponatremia',
    '276.2': 'Acidosis',
    '276.5': 'Volume depletion',
    '276.51': 'Dehydration',
    '276.52': 'Hypovolemia',
    '276.7': 'Hyperpotassemia',
    '276.8': 'Hypopotassemia',
    '277.39': 'Other amyloidosis',
    '278.00': 'Obesity, unspecified',
    '284.8': 'Other specified aplastic anemias',
    '285.1': 'Acute posthemorrhagic anemia',
    '285.21': 'Anemia in chronic kidney disease',
    '285.9': 'Anemia, unspecified',
    '286.7': 'Acquired coagulation factor deficiency',
    '287.5': 'Thrombocytopenia, unspecified',
    '289.59': 'Other diseases of spleen',
    '291.0': 'Alcohol withdrawal delirium',
    '291.81': 'Alcohol withdrawal',
    '293.0': 'Delirium due to conditions classified elsewhere',
    '300.00': 'Anxiety state, unspecified',
    '305.1': 'Tobacco use disorder',
    '311': 'Depressive disorder, not elsewhere classified',
    '327.23': 'Obstructive sleep apnea (adult) (pediatric)',
    '336.3': 'Myelopathy in other diseases classified elsewhere',
    '343.8': 'Other specified infantile cerebral palsy',
    '348.39': 'Other encephalopathy',
    '349.82': 'Toxic encephalopathy',
    '357.2': 'Polyneuropathy in diabetes',
    '357.82': 'Critical illness polyneuropathy',
    '362.21': 'Retrolental fibroplasia',
    '366.9': 'Unspecified cataract',
    '379.21': 'Vitreous degeneration',
    '401.9': 'Unspecified essential hypertension',
    '403.90': 'Hypertensive renal disease, unspecified, without mention of renal failure',
    '403.91': 'Hypertensive renal disease, unspecified, with renal failure',
    '410.71': 'Acute myocardial infarction, subendocardial infarction, initial episode of care',
    '411.1': 'Intermediate coronary syndrome',
    '412': 'Old myocardial infarction',
    '414.00': 'Coronary atherosclerosis of unspecified type of vessel, native or graft',
    '414.01': 'Coronary atherosclerosis of native coronary artery',
    '415.0': 'Acute cor pulmonale',
    '415.11': 'Iatrogenic pulmonary embolism and infarction',
    '416.8': 'Other chronic pulmonary heart diseases',
    '416.9': 'Chronic pulmonary heart disease, unspecified',
    '424.0': 'Mitral valve disorders',
    '424.1': 'Aortic valve disorders',
    '425.4': 'Other primary cardiomyopathies',
    '427.1': 'Paroxysmal ventricular tachycardia',
    '427.31': 'Atrial fibrillation',
    '427.32': 'Atrial flutter',
    '427.5': 'Cardiac arrest',
    '427.89': 'Other specified cardiac dysrhythmias',
    '428.0': 'Congestive heart failure, unspecified',
    '428.23': 'Systolic heart failure, acute on chronic',
    '428.32': 'Diastolic heart failure, chronic',
    '428.33': 'Diastolic heart failure, acute on chronic',
    '430': 'Subarachnoid hemorrhage',
    '431': 'Intracerebral hemorrhage',
    '432.1': 'Subdural hemorrhage',
    '437.0': 'Cerebral atherosclerosis',
    '438.89': 'Other late effects of cerebrovascular disease',
    '443.9': 'Peripheral vascular disease, unspecified',
    '458.29': 'Other iatrogenic hypotension',
    '458.9': 'Hypotension, unspecified',
    '459.0': 'Hemorrhage, unspecified',
    '482.9': 'Bacterial pneumonia, unspecified',
    '486': 'Pneumonia, organism unspecified',
    '491.21': 'Obstructive chronic bronchitis with (acute) exacerbation',
    '491.8': 'Other chronic bronchitis',
    '493.90': 'Asthma, unspecified type, without mention of status asthmaticus',
    '496': 'Chronic airway obstruction, not elsewhere classified',
    '507.0': 'Pneumonitis due to inhalation of food or vomitus',
    '511.9': 'Unspecified pleural effusion',
    '515': 'Postinflammatory pulmonary fibrosis',
    '518.0': 'Pulmonary collapse',
    '518.5': 'Pulmonary insufficiency following trauma and surgery',
    '518.81': 'Acute respiratory failure',
    '518.83': 'Chronic respiratory failure',
    '519.4': 'Disorders of diaphragm',
    '530.81': 'Esophageal reflux',
    '530.82': 'Esophageal hemorrhage',
    '536.2': 'Persistent vomiting',
    '536.3': 'Gastroparesis',
    '560.1': 'Paralytic ileus',
    '560.81': 'Intestinal or peritoneal adhesions with obstruction [postoperative] [postinfection]',
    '564.89': 'Other functional disorders of intestine',
    '568.81': 'Hemoperitoneum (nontraumatic)',
    '571.2': 'Alcoholic cirrhosis of liver',
    '571.5': 'Cirrhosis of liver without mention of alcohol',
    '576.1': 'Cholangitis',
    '576.2': 'Obstruction of bile duct',
    '577.8': 'Other specified diseases of pancreas',
    '578.9': 'Hemorrhage of gastrointestinal tract, unspecified',
    '584.5': 'Acute renal failure with lesion of tubular necrosis',
    '584.9': 'Acute renal failure, unspecified',
    '585.6': 'End stage renal disease',
    '585.9': 'Chronic kidney disease, unspecified',
    '588.0': 'Renal osteodystrophy',
    '599.0': 'Urinary tract infection, site not specified',
    '600.00': 'Hypertrophy (benign) of prostate without urinary obstruction and other lower urinary tract symptoms (LUTS)',
    '611.1': 'Hypertrophy of breast',
    '642.33': 'Transient hypertension of pregnancy, antepartum',
    '644.21': 'Early onset of delivery, delivered, with or without mention of antepartum condition',
    '648.11': 'Thyroid dysfunction of mother, with delivery',
    '648.91': 'Other current conditions classifiable elsewhere of mother, with delivery',
    '66.0': 'Salpingotomy and salpingostomy',
    '666.24': 'Delayed and secondary postpartum hemorrhage, postpartum',
    '674.04': 'Cerebrovascular disorder, postpartum',
    '691.0': 'Diaper or napkin rash',
    '707.03': 'Decubitus ulcer, lower back',
    '719.65': 'Other symptoms referable to joint of pelvic region and thigh',
    '729.89': 'Other musculoskeletal symptoms referable to limbs',
    '733.00': 'Osteoporosis, unspecified',
    '741.00': 'With hydrocephalus, spina bifida, unspecified region',
    '745.69': 'Other endocardial cushion defects',
    '747.83': 'Persistent fetal circulation',
    '751.2': 'Atresia and stenosis of large intestine, rectum, and anal canal, congenital',
    '753.15': 'Renal dysplasia',
    '756.79': 'Other congenital anomalies of abdominal wall',
    '760.75': 'Cocaine affecting fetus via placenta or breast milk',
    '765.02': 'Extreme immaturity, 500-749 grams',
    '765.03': 'Extreme immaturity, 750-999 grams',
    '765.15': 'Other preterm infants, 1,250-1,499 grams',
    '765.16': 'Other preterm infants, 1,500-1,749 grams',
    '765.17': 'Other preterm infants, 1,750-1,999 grams',
    '765.18': 'Other preterm infants, 2,000-2,499 grams',
    '765.26': '31-32 completed weeks of gestation',
    '765.28': '35-36 completed weeks of gestation',
    '766.1': 'Other "heavy-for-dates" infants',
    '769': 'Respiratory distress syndrome in newborn',
    '770.0': 'Congenital pneumonia',
    '770.12': 'Meconium aspiration with respiratory symptoms',
    '770.2': 'Interstitial emphysema and related conditions of newborn',
    '770.4': 'Primary atelectasis of newborn',
    '770.6': 'Transitory tachypnea of newborn',
    '770.82': 'Other apnea of newborn',
    '770.84': 'Respiratory failure of newborn',
    '770.89': 'Other respiratory problems after birth',
    '771.8': 'Other infection specific to the perinatal period',
    '771.81': 'Septicemia [sepsis] of newborn',
    '771.82': 'Urinary tract infection of newborn',
    '771.89': 'Other infections specific to the perinatal period',
    '772.10': 'Intraventricular hemorrhage, unspecified grade',
    '772.12': 'Intraventricular hemorrhage, grade II',
    '772.8': 'Other specified hemorrhage of fetus or newborn',
    '774.2': 'Neonatal jaundice associated with preterm delivery',
    '774.39': 'Other neonatal jaundice due to delayed conjugation from other causes',
    '774.6': 'Unspecified fetal and neonatal jaundice',
    '775.0': 'Syndrome of "infant of a diabetic mother"',
    '775.5': 'Other transitory neonatal electrolyte disturbances',
    '775.6': 'Neonatal hypoglycemia',
    '775.9': 'Unspecified endocrine and metabolic disturbances specific to the fetus and newborn',
    '776.1': 'Transient neonatal thrombocytopenia',
    '776.4': 'Polycythemia neonatorum',
    '776.5': 'Congenital anemia',
    '776.6': 'Anemia of prematurity',
    '777.1': 'Meconium obstruction in fetus or newborn',
    '777.4': 'Transitory ileus of newborn',
    '778.3': 'Other hypothermia of newborn',
    '778.4': 'Other disturbances of temperature regulation of newborn',
    '779.3': 'Feeding problems in newborn',
    '779.5': 'Drug withdrawal syndrome in newborn',
    '779.81': 'Neonatal bradycardia',
    '779.89': 'Other specified conditions originating in the perinatal period',
    '806.29': 'Closed fracture of T(7)-T(12) level with other specified spinal cord injury',
    '807.2': 'Closed fracture of sternum',
    '861.32': 'Laceration of lung with open wound into thorax',
    '909.2': 'Late effect of radiation',
    '93.9': 'Respiratory therapy',
    '965.02': 'Poisoning by methadone',
    '995.91': 'Sepsis',
    '995.92': 'Severe sepsis',
    '996.82': 'Complications of transplanted liver',
    '997.1': 'Cardiac complications, not elsewhere classified',
    '998.11': 'Hemorrhage complicating a procedure',
    '998.12': 'Hematoma complicating a procedure',
    '998.31': 'Disruption of internal operation wound',
    '998.59': 'Other postoperative infection',
    '998.83': 'Non-healing surgical wound',
    'E878.2': 'Surgical operation with anastomosis, bypass, or graft, with natural or artificial tissues used as implant causing abnormal patient reaction, or later complication, without mention of misadventure at time of operation',
    'E878.8': 'Other specified surgical operations and procedures causing abnormal patient reaction, or later complication, without mention of misadventure at time of operation',
    'E879.8': 'Other specified procedures as the cause of abnormal reaction of patient, or of later complication, without mention of misadventure at time of procedure',
    'E935.2': 'Other opiates and related narcotics causing adverse effects in therapeutic use',
    'E942.9': 'Other and unspecified agents primarily affecting the cardiovascular system causing adverse effects in therapeutic use',
    'V05.3': 'Need for prophylactic vaccination and inoculation against viral hepatitis',
    'V10.3': 'Personal history of malignant neoplasm of breast',
    'V10.46': 'Personal history of malignant neoplasm of prostate',
    'V12.09': 'Other personal history of infectious and parasitic disease',
    'V12.51': 'Personal history of venous thrombosis and embolism',
    'V12.59': 'Other personal history of diseases of circulatory system',
    'V15.82': 'History of tobacco use',
    'V17.49': 'Family history of other cardiovascular diseases',
    'V20.2': 'Routine infant or child health check',
    'V27.0': 'Mother with single liveborn',
    'V27.2': 'Mother with twins, both liveborn',
    'V29.0': 'Observation for suspected infectious condition',
    'V29.3': 'Observation for suspected genetic or metabolic condition',
    'V29.8': 'Observation for other specified suspected condition',
    'V30.00': 'Single liveborn, born in hospital, delivered without mention of cesarean section',
    'V30.01': 'Single liveborn, born in hospital, delivered by cesarean section',
    'V45.01': 'Cardiac pacemaker in situ',
    'V45.72': 'Acquired absence of intestine (large) (small)',
    'V45.76': 'Acquired absence of lung',
    'V45.81': 'Postsurgical aortocoronary bypass status',
    'V45.82': 'Percutaneous transluminal coronary angioplasty, postsurgical status',
    'V50.2': 'Routine or ritual circumcision',
    'V58.41': 'Encounter for planned post-operative wound closure',
    'V58.61': 'Encounter for long-term (current) use of anticoagulants',
    'V58.67': 'Encounter for long-term (current) use of insulin',
    'V58.83': 'Encounter for therapeutic drug monitoring',
    'V64.1': 'Surgical or other procedure not carried out because of contraindication',
    'V72.1': 'Examination of ears and hearing',
    'V85.30': 'Body Mass Index 30.0-30.9, adult',
    'V85.39': 'Body Mass Index 39.0-39.9, adult',
    'V85.4': 'Body Mass Index 40 and over, adult',
}
